Use kubectl replace instead of patch to restore config-gc (#11062)
The following commands in test/e2e-tests.sh:

```
GC_CONFIG=$(kubectl get cm "config-gc" -n "${SYSTEM_NAMESPACE}" -o yaml)
kubectl patch cm "config-gc" -n ${SYSTEM_NAMESPACE} -p ${GC_CONFIG}
```

It always failing with the following error. This is replicable in the local env.

```
2021/03/29 02:42:48 Getting artifacts dir from prow
Error: bad flag syntax: ---------------------------------------
```

Hence this patch fixes it by using `kubectl replace` instead of `patch`.