Command group name has to be `clusters` instead of `cluster` for (step 5); the `get-credentials` sample command (#1125)
Failed with group name `cluster`:
```
± |master ✓| → gcloud container cluster get-credentials ssuresh-knative-dev
ERROR: (gcloud.container) Invalid choice: 'cluster'. Did you mean 'clusters'?
Usage: gcloud container [optional flags] <group | command>
  group may be           builds | clusters | images | node-pools | operations
  command may be         get-server-config

For detailed information on this command and its flags, run:
  gcloud container --help
```

Works with group name `clusters`:
```
± |master ✓| → gcloud container clusters get-credentials ssuresh-knative-dev
Fetching cluster endpoint and auth data.
kubeconfig entry generated for ssuresh-knative-dev.
```