Add validation check to tag name
`tag` name is used for sub route's domain URL, but we can modify it to
any value like "foo@" or "foo.bar".

This patch adds validation check to the tag name which is same
validation with Revision name.

ERROR AFTER THIS PATCH:

```
$ kubectl edit ksvc hello-example
error: services.serving.knative.dev "hello-example" could not be patched: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: invalid value: not a DNS 1035 label: [a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]: spec.traffic.tag[0]
You can run `kubectl replace -f /tmp/kubectl-edit-bm06i.yaml` to try this update again.
```